version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
#    command: ['python', 'main.py']
    restart: always
    volumes:
#      - .:/app
      - ./app:/app
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
  db:
    image: "postgres:latest"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=iot_db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - '5432:5432'
volumes:
  postgres_data:
